name: Django Basic Dev Tests

on: [push]

env:
  MODE: Test
jobs:
  name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
  runs-on: "${{ matrix.os }}"

  strategy:
    fail-fast: false
    matrix:
      os:
        - ubuntu-latest
        - windows-latest
      python-version:
        - "3.7"
        - "3.8"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install requirements
        run: |
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          pytest --cov=leopards tests/
